version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /home/mitsuharu/projetos/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@teste.com"
      PGADMIN_DEFAULT_PASSWORD: "teste123"
    ports:
      - "6543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    command: start-dev

networks:
  postgres-compose-network:
    driver: bridge